spring.application.name=TestSpring
spring.datasource.url=jdbc:mysql://localhost:3306/sprfood_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=abc123!@#

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
jwt.secret=ZHV5S1R5bUZ1bGxTZWNyZXRLZXlGb3JIUzI1NklzVmVyeVNlY3VyZQ==
jwt.expiration=86400000
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# C?u hình static resource ?? truy c?p file upload
spring.web.resources.static-locations=classpath:/static/,classpath:/public/,classpath:/resources/,classpath:/META-INF/resources/,file:uploads/

# Gi?i h?n kích th??c upload
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB